### ISSUE TITLE
Create named releases for the latest named release of DNX

### ISSUE THREAD

**Issue by Alxandr** [fsprojects/fsharp-dnx#11]
Dnx mainly releases on two feeds. NuGet and `aspnetvnext` on MyGet. The master branch of fsharp-dnx should always be up to date with the `aspnetvnext` feed, so that it works with the latest preview builds of DNX, however, this means that there are currently no way for people opting to go for the less unstable named preview builds of DNX to use F# with DNX. Creating these named releases will be a somewhat manual process, and guidelines for creating them in the future should be recorded as well.

**Comment by jbfp** [comment]
Would it be an idea, when RC1 releases, to keep a 'release'/master branch that matches the release branch of DNX and then have a 'dev' branch that works like master at the moment, i.e. it works on more unstable platforms?

**Comment by Alxandr** [comment]
I'm thinking of making a release branch, yes. Don't see the point in both
release, dev and master though.

**Comment by jbfp** [comment]
Yeah in this case release and master would be same thing with dev as the 'cutting edge' or something like that, but I guess it may not be worth it trying to keep up with the dnx dev branch, and instead just update release whenever dnx/aspnet5 releases a new version

**Comment by Alxandr** [comment]
Master is edge, and is (attempted at least) to be inline with edge. A new
release branch will be created for releases.

**Comment by Alxandr** [comment]
https://github.com/fsprojects/fsharp-dnx/releases/tag/v1.0.0-beta1
