### ISSUE TITLE
Build broke

### ISSUE THREAD

**Issue by Alxandr** [fsprojects/fsharp-dnx#18]
Error message from CI:

```
System.InvalidCastException: Unable to cast object of type 'FSharp.Dnx.FSharpProjectCompiler' to type 'Microsoft.Dnx.Compilation.IProjectCompiler'.
```

Probably just another DNX refactoring (renaming of classes/namespaces).

**Comment by jbfp** [comment]
It seems that [this](https://github.com/aspnet/dnx/commit/30e9fcf50ad45b602c864533fb723a86713ed8bb) might be the culprit
