### ISSUE TITLE
Samples compile as C#?

### ISSUE THREAD

**Issue by samritchie** [fsprojects/fsharp-dnx#3]
I’m running on mono 3.1.2 and have successfully built YoloDev.Dnx.FSharp, but when I try to build the sample projects with `dnu build`, it appears to try and compile them as C#, with a bunch of output like:

```
YoloDev.Dnx.FSharp/sample/HelloFSharp/hello.fs(1,22): error CS1514: { expected
YoloDev.Dnx.FSharp/sample/HelloFSharp/hello.fs(3,6): error CS1520: Method must have a return type
YoloDev.Dnx.FSharp/sample/HelloFSharp/hello.fs(3,16): error CS1002: ; expected
```

I’m unsure if I need to do something else to build as FSharp?

**Comment by Alxandr** [comment]
Ok, so that's definitely weird. What version of `dnx` are you rocking?

Also, come find me at https://jabbr.net/#/rooms/YoloDev. Makes this back and forth a bit easier :)

**Comment by samritchie** [comment]
dnx beta4 has issues - beta5 invokes the Sharp compiler as expected.
