### ISSUE TITLE
Refactor: Remove project.fsharp.json

### ISSUE THREAD

**Issue by Alxandr** [fsprojects/fsharp-dnx#7]
It might be possible to soly use the APIs from `Project` in DNX, while still maintaining file order. If not, simply merge the two files together somehow, instead of keeping them as two files.

**Comment by jbfp** [comment]
I can look into this.
I was thinking that you could just have an "fsharp" configuration section in the project.json alongside the "dependencies" and "commands" and whatnot.

``` json
{
  "version": "1.0.0-*",
  "description": "",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "FSharp.Dnx": { "type": "build", "version": "" },
    "Microsoft.AspNet.Testing": "1.0.0-*",
    "xunit.runner.aspnet": "2.0.0-aspnet-*"
  },

  "commands": {
    "test": "xunit.runner.aspnet"
  },

  "frameworks": {
    "dnx451": { }
  },

  "compiler": {
    "name": "F#",
    "compilerAssembly": "FSharp.Dnx",
    "compilerType": "FSharp.Dnx.FSharpProjectCompiler"
  },

  "fsharp": {
    "autoDiscoverFsi": true,
    "files": [
      "test.fs"
    ]
  }
}
```

Let me know what you think

**Comment by Alxandr** [comment]
Yeah, that was my thoughts too. At least for the initial version.
